### ISSUE TITLE
HConsign's table should regularly garbage collect dropped weak pointers

### ISSUE THREAD

**Issue by alpire** [AdrienChampion/hashconsing#2]
First, thanks for writing this crate. It's been super useful!

When writing a fuzzing harness for code relying on `hashconsing`, I detected that `HConsign` increasingly accumulates state. I see tens of thousands of entries in `HConsign.table` even after dropping all the hashconsed elements.

I'm not sure what a good solution would be here, but options might include:
- using https://docs.rs/weak-table/0.3.0/weak_table/. It garbage collects on resize, which is a great place to do it since the operation is already O(N) due to rehasing. However, this crate has its own implementation of a hash table, and it'll likely be quite a bit slower than the stdlib's one.
- exposing a method to give users the ability to GC dropped entries whenever convenient to them.

**Comment by AdrienChampion** [comment]
> First, thanks for writing this crate. It's been super useful!

Thank you, I appreciate it :)

> When writing a fuzzing harness for code relying on `hashconsing`, I detected that `HConsign` increasingly accumulates state. I see tens of thousands of entries in `HConsign.table` even after dropping all the hashconsed elements.

Right. This is not very relevant for my typical use case, so I missed it. Now that you mention it, it's obvious to me that `hashconsing` should address this problem.

>     * exposing a method to give users the ability to GC dropped entries whenever convenient to them.

I'm going for this one. I expect most users looking for this feature to have easily identifiable points in the code where they know some elements where created and dropped, and collecting dead elements is worth it.

So here's [what I did][pr] on the `HashConsign` trait:
- added a [`collect`][collect] method (doc [here][collect doc])
- lifted [`shrink_to_fit`][others] and [`reserve`][others] from `HashMap`
- added a [`collect_to_shrink`][others] convenience method

Note that `collect` also makes sure the internal element UID counter is as low as possible when it's done collecting.

I think this answers the problem reasonably well, what do you think?

[pr]: https://github.com/AdrienChampion/hashconsing/pull/4
[collect doc]: https://github.com/AdrienChampion/hashconsing/blob/collect/src/lib.rs#L560-L564
[collect]: https://github.com/AdrienChampion/hashconsing/blob/collect/src/lib.rs#L595-L619
[others]: https://github.com/AdrienChampion/hashconsing/blob/collect/src/lib.rs#L621-L632

**Comment by AdrienChampion** [comment]
> I think this answers the problem reasonably well.

Let me clarify this a bit.

The elements of the consign are stored in a random order since they are in `table`, a regular `HashMap` with the default `Hasher`. Say now element `e` is dead (no strong reference to it), and say also `sub_e` is a sub-element of `e` that only `e` references.

Then as I go through the table to collect, if I see `sub_e` before `e` its strong count will not be 0 because `e` still references it. Later I will drop `e` because it's dead, bringing `sub_e`'s strong count to 0, but it's too late. So I have to keep applying this collection operation as long I collect something until I reach a fixed point.

This brings the complexity of this operation to something like `n*d` where `d` is the maximal depth of the dead elements in the map and `n` is the number of elements in the map.

The ideal case would be for `table` to store elements in a reverse-structural order, typically by UID reverse-order. That way I know that I always see all elements referencing `sub` before I see `sub`, and collection can be done in a single iteration.

Trying to be in this ideal case implies changing the code quite a bit and loosing the security properties of the default-`HashMap`'s. I'm not very keen on doing that right now; I don't rely on these security properties myself, but others might.

Hence the solution I implemented.

**Comment by alpire** [comment]
Oh wow, thanks for adding those functions so quickly. The PR looks great, and the functions you added are exactly what I could use. I like how it gives users control, since as you said, they would now best when it's a good time to do it.

> Then as I go through the table to collect, if I see `sub_e` before `e` its strong count will not be 0 because `e` still references it. Later I will drop `e` because it's dead, bringing `sub_e`'s strong count to 0, but it's too late. So I have to keep applying this collection operation as long I collect something until I reach a fixed point.

My understanding is that the table only holds weak references to the elements, which do not count towards ownership. As such, when `e` is dropped, `sub_e` should be dropped as well, even if the table still holds a weak reference to `e`, right? If that's the case, both `e` and `sub_e` should be collectable in a single linear pass over the table values.

**Comment by AdrienChampion** [comment]
> My understanding is that the table only holds weak references to the elements, which do not count towards ownership. As such, when `e` is dropped, `sub_e` should be dropped as well, even if the table still holds a weak reference to `e`, right? If that's the case, both `e` and `sub_e` should be collectable in a single linear pass over the table values.

No, unfortunately. `sub_e` is a sub-element of `e`, meaning `e` stores a (strong) `Arc` to `sub_e`. When I go through the table and encounter `sub_e`, its strong-count is `1` since `e` references it. So I keep the entry `(sub_e, weak)` and move on.

Later, I remove the entry for `e` because it's dead, which causes to drop the last (strong) `Arc` to `sub_e`. At this point, the entry for `(sub_e, weak)` is still inside the table. The strong count is now `0`, but to known that I can remove it I have to go through the whole table again. (Notice that hashconsing has no way to know `sub_e` is a sub-element of `e`, it cannot access the kids of your arbitrary enum.) And so on, recursively.

I'm not sure if that's what you mean, but the value pointed to is indeed dropped since there's no strong refs to it anymore. This happens in the current version too, there's no need for collection, it's a consequence of how `Arc`s work. But the entry for `sub_e`, which stores a version of `sub_e` (the key) and a weak ref (the value), is still in the table. In particular, the sub-elements of `sub_e` still have strong references to them because of the key.

I'm not sure this explanation is very clear, let me know if you understand it. If not, look closely at the type of the table in the consign, the type of the keys in particular. It seems to me that might be the part you're missing.

--------

Aside from having a special order in the table as I mentioned, I see two (bad, I think) ways to handle this.

The first is to somehow store a reference to the factory inside hashconsed elements. When they're dropped, I can check whether the strong count is `0` in which case I can go remove the entry directly, recursively. There's a bunch of issues with this, not the least of which is that it increases the size of hashconsed elements significantly for a feature some might not care about.

The second is to ask users to expose the kids of an element. That way, when I collect, I can know which sub-elements I need to remove because they're dead too and I can use that information to do something more clever. I'm not fond of this either as it makes me rely on user code for my collection strategy to work.

I think the current solution is better as it gives (safe) control to the user regarding how collecting is done, without any impact on hashconsed or raw elements.

**Comment by alpire** [comment]
>  If not, look closely at the type of the table in the consign, the type of the keys in particular. It seems to me that might be the part you're missing.

Oh, that's indeed what I was missing. Thanks for taking the time to explain it.

> I think the current solution is better as it gives (safe) control to the user regarding how collecting is done, without any impact on hashconsed or raw elements.

I agree. I was trying to think how the consign could avoid using strong references to `T` as keys, but I haven't found a solution that wouldn't add annoying requirements on `T`.
